/media/ava/DATA2/Raj/rajkumar/bin/python: can't open file 'src/tools/check_onnx.py': [Errno 2] No such file or directory
/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 2538247) of binary: /media/ava/DATA2/Raj/rajkumar/bin/python
Traceback (most recent call last):
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/ava/DATA2/Raj/rajkumar/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/tools/check_onnx.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-30_12:08:15
  host      : benz
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 2538247)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
